language: java

matrix:
  include:
# 16
    - env:
      - JDK='Open JDK 16'
      - MAVEN_PROFILE="-Pcdi-2.0"
      jdk: openjdk16

    - env:
      - JDK='Open JDK 16'
      - MAVEN_PROFILE="-Pcdi-1.2"
      jdk: openjdk16

    - env:
      - JDK='Open JDK 16'
      - MAVEN_PROFILE="-Pcdi-1.1"
      jdk: openjdk16

# 15
    - env:
      - JDK='Open JDK 15'
      - MAVEN_PROFILE="-Pcdi-2.0"
      jdk: openjdk15

    - env:
      - JDK='Open JDK 15'
      - MAVEN_PROFILE="-Pcdi-1.2"
      jdk: openjdk15

    - env:
      - JDK='Open JDK 15'
      - MAVEN_PROFILE="-Pcdi-1.1"
      jdk: openjdk15

# 11
    - env:
      - JDK='Open JDK 11'
      - MAVEN_PROFILE="-Pcdi-2.0"
      jdk: openjdk11

    - env:
      - JDK='Open JDK 11'
      - MAVEN_PROFILE="-Pcdi-1.2"
      jdk: openjdk11

    - env:
      - JDK='Open JDK 11'
      - MAVEN_PROFILE="-Pcdi-1.1"
      jdk: openjdk11

# 8
    - env:
      - JDK='Open JDK 8'
      - MAVEN_PROFILE="-Pcdi-2.0"
      jdk: openjdk8

    - env:
      - JDK='Open JDK 8'
      - MAVEN_PROFILE="-Pcdi-1.2"
      jdk: openjdk8

    - env:
      - JDK='Open JDK 8'
      - MAVEN_PROFILE="-Pcdi-1.1"
      jdk: openjdk8
      
script:
  - ./mvnw test -B -V $MAVEN_PROFILE
